ASAC-marketplace/backend

build.gradle, src/main/java/market/demo/controller/MemberController.java, src/main/java/market/demo/domain/Member.java, src/main/java/market/demo/domain/Payment.java, src/main/java/market/demo/domain/config/SecurityConfig.java, src/main/java/market/demo/dto/registermember/EmailAvailabilityDto.java, src/main/java/market/demo/dto/registermember/LoginIdAvailabilityDto.java, src/main/java/market/demo/dto/registermember/MemberRegistrationDto.java, src/main/java/market/demo/repository/MemberRepository.java, src/main/java/market/demo/service/MemberService.java
=> 5 api 일반 회원가입 api

src/main/java/market/demo/controller/MemberController.java, src/main/java/market/demo/dto/MemberDeletionRequest.java, src/main/java/market/demo/exception/MemberNotFoundException.java, src/main/java/market/demo/service/MemberService.java
=> 28-api-회원-탈퇴-api

src/main/java/market/demo/domain/config/SecurityConfig.java
=> 27-api-회원-로그아웃-api

src/main/java/market/demo/controller/MemberController.java, src/main/java/market/demo/dto/recoverypassword/RecoveryPasswordRequestDto.java, src/main/java/market/demo/repository/MemberRepository.java, src/main/java/market/demo/service/MemberService.java
=> Feat: 비밀번호 찾기(재설정) 시 로그인 아이디, 이메일 유효성 검증 api 추가

.gitignore
=> Docs: gitignore 수정?

src/main/java/market/demo/controller/MemberController.java, src/main/java/market/demo/domain/Member.java, src/main/java/market/demo/dto/recoverypassword/PasswordChangeDto.java, src/main/java/market/demo/repository/MemberRepository.java, src/main/java/market/demo/service/MemberService.java
=> Feat: 비밀번호 찾기

src/main/java/market/demo/advice/GlobalExceptionHandler.java
=> Feat: Member쪽 ExceptinoHandler 추가

src/main/java/market/demo/domain/Item.java, src/main/java/market/demo/domain/Member.java, src/main/java/market/demo/domain/Promotion.java, src/main/java/market/demo/domain/Wishlist.java, src/main/java/market/demo/domain/status/PromotionType.java
=> Feat: 프로모션, 위시리스트 엔티티 추가

build.gradle, src/main/java/market/demo/controller/ItemController.java, src/main/java/market/demo/domain/config/QuerydslConfiguration.java, src/main/java/market/demo/domain/item/Category.java, src/main/java/market/demo/domain/item/Item.java, src/main/java/market/demo/domain/item/ItemDetail.java, src/main/java/market/demo/domain/item/ItemTestDataCreator.java, src/main/java/market/demo/domain/item/Review.java, src/main/java/market/demo/dto/item/ItemDto.java, src/main/java/market/demo/repository/ItemReposistory.java, src/main/java/market/demo/service/ItemService.java
=> Feat: 신상품 순으로 정렬, 페이징 해서 json으로 반환하는 api기능 구현

src/main/java/market/demo/DemoApplication.java, src/main/java/market/demo/controller/item/ItemController.java, src/main/java/market/demo/domain/etc/PromotionScheduler.java, src/main/java/market/demo/service/ItemService.java
스케줄로 주말에 상품 랜덤으로 자동 주말특가 적 기능 추가
- Projects 이슈 링크
-
=> 10-api-메인-주말특가-api 

src/main/java/market/demo/controller/MemberController.java, src/main/java/market/demo/domain/item/Item.java, src/main/java/market/demo/domain/item/ItemDetail.java, src/main/java/market/demo/domain/item/Review.java, src/main/java/market/demo/dto/itemdetailinfo/ItemDetailDto.java, src/main/java/market/demo/repository/CouponRepository.java, src/main/java/market/demo/repository/ItemDetailRepository.java, src/main/java/market/demo/repository/ItemReposistory.java, src/main/java/market/demo/repository/MemberRepository.java, src/main/java/market/demo/service/ItemService.java, src/main/java/market/demo/service/MemberService.java
- exception 정리
- 혹시 멤버 정보도 자동 create 해주실 수 있나요? 리뷰에 멤버 정보가 없어서 불러오기는데 제약이 있습니다.
=> code 정리  및 수정 entity 반영

build.gradle, src/main/java/market/demo/controller/MemberController.java, src/main/java/market/demo/domain/ApplicationTestDataInitializer.java, src/main/java/market/demo/domain/item/Item.java, src/main/java/market/demo/domain/item/ItemDetail.java, src/main/java/market/demo/domain/item/ItemTestDataCreator.java, src/main/java/market/demo/domain/item/Review.java, src/main/java/market/demo/domain/member/Member.java, src/main/java/market/demo/domain/member/MemberTestDataCreator.java, src/main/java/market/demo/domain/member/jwt/TokenProvider.java, src/main/java/market/demo/service/ItemService.java
=> 테스트용 데이터 추가

src/main/java/market/demo/controller/Search/SearchController.java, src/main/java/market/demo/domain/search/ItemSearchCondition.java, src/main/java/market/demo/dto/search/ItemSearchDto.java, src/main/java/market/demo/repository/ItemReposistory.java, src/main/java/market/demo/repository/ItemRepository.java, src/main/java/market/demo/repository/ItemRepositoryCustom.java, src/main/java/market/demo/repository/ItemRepositoryImpl.java, src/main/java/market/demo/service/SearchService.java
=> 12 api 일반 검색 api

src/main/java/market/demo/controller/Search/SearchController.java, src/main/java/market/demo/dto/search/ItemAutoDto.java, src/main/java/market/demo/repository/ItemRepositoryCustom.java, src/main/java/market/demo/repository/ItemRepositoryImpl.java, src/main/java/market/demo/service/SearchService.java
=> 15 api 키워드 자동 완성 api

src/main/java/market/demo/controller/order/OrderController.java, src/main/java/market/demo/domain/ApplicationTestDataInitializer.java, src/main/java/market/demo/domain/order/OrderTestDataCreator.java, src/main/java/market/demo/dto/order/OrderDto.java, src/main/java/market/demo/dto/order/OrderItemDto.java, src/main/java/market/demo/repository/OrderItemRepository.java, src/main/java/market/demo/repository/OrderRepository.java, src/main/java/market/demo/service/ItemService.java, src/main/java/market/demo/service/OrderService.java
- Projects 이슈 링크
- 현재 order init으로 data 생성 되는 거 일단 막았어요, 주문서 만드는 것까지 완료했습니다. 피드백 부탁드려요
=> 19 ëapi done

src/main/java/market/demo/advice/GlobalExceptionHandler.java, src/main/java/market/demo/controller/LoginTestController.java, src/main/java/market/demo/controller/inquiry/InquiryController.java, src/main/java/market/demo/domain/inquiry/Inquiry.java, src/main/java/market/demo/domain/status/InquiryStatus.java, src/main/java/market/demo/dto/inquiry/InquiryRequest.java, src/main/java/market/demo/dto/inquiry/InquiryResponse.java, src/main/java/market/demo/dto/payment/PaymentResponseDto.java, src/main/java/market/demo/exception/EntityNotFoundException.java, src/main/java/market/demo/exception/InvalidDataException.java, src/main/java/market/demo/repository/InquiryRepository.java, src/main/java/market/demo/service/ItemService.java, src/main/java/market/demo/service/OrderService.java, src/main/java/market/demo/service/inquiry/InquiryService.java
=> 21 api 11문의 api

src/main/java/market/demo/advice/GlobalExceptionHandler.java, src/main/java/market/demo/controller/inquiry/InquiryController.java, src/main/java/market/demo/controller/item/ItemController.java, src/main/java/market/demo/controller/member/LoginTestController.java, src/main/java/market/demo/controller/search/SearchController.java, src/main/java/market/demo/domain/ApplicationTestDataInitializer.java, src/main/java/market/demo/domain/inquiry/Inquiry.java, src/main/java/market/demo/domain/member/Member.java, src/main/java/market/demo/domain/member/MemberTestDataCreator.java, src/main/java/market/demo/domain/order/Cart.java, src/main/java/market/demo/domain/order/OrderTestDataCreator.java, src/main/java/market/demo/domain/search/ItemSearchCondition.java, src/main/java/market/demo/domain/search/SearchHistory.java, src/main/java/market/demo/domain/status/InquiryStatus.java, src/main/java/market/demo/dto/inquiry/InquiryRequest.java, src/main/java/market/demo/dto/inquiry/InquiryResponse.java, src/main/java/market/demo/dto/mypage/MyPageDto.java, src/main/java/market/demo/dto/payment/PaymentResponseDto.java, src/main/java/market/demo/exception/EntityNotFoundException.java, src/main/java/market/demo/exception/InvalidDataException.java, src/main/java/market/demo/repository/InquiryRepository.java, src/main/java/market/demo/repository/SearchReposirory.java, src/main/java/market/demo/service/CartService.java, src/main/java/market/demo/service/ItemService.java, src/main/java/market/demo/service/OrderService.java, src/main/java/market/demo/service/SearchService.java, src/main/java/market/demo/service/inquiry/InquiryService.java, src/main/java/market/demo/service/payment/PaymentService.java
=> Feat: 급상승 검색어

src/main/java/market/demo/domain/ApplicationTestDataInitializer.java, src/main/java/market/demo/domain/order/Payment.java, src/main/java/market/demo/service/payment/ExternalPaymentGateway.java, src/main/java/market/demo/service/payment/PaymentService.java
=> Refactor: PaymentService

src/main/java/market/demo/controller/member/MemberController.java, src/main/java/market/demo/controller/search/SearchController.java, src/main/java/market/demo/domain/ApplicationTestDataInitializer.java, src/main/java/market/demo/domain/member/Member.java, src/main/java/market/demo/domain/member/MemberTestDataCreator.java, src/main/java/market/demo/domain/order/Cart.java, src/main/java/market/demo/domain/order/CartItem.java, src/main/java/market/demo/domain/order/OrderItem.java, src/main/java/market/demo/domain/search/AgeGenderFrequency.java, src/main/java/market/demo/domain/search/SearchKeyword.java, src/main/java/market/demo/domain/status/AgeStatus.java, src/main/java/market/demo/domain/status/GenderStatus.java, src/main/java/market/demo/dto/cart/CartDto.java, src/main/java/market/demo/dto/cart/CartItemDto.java, src/main/java/market/demo/dto/itemdetailinfo/CouponDto.java, src/main/java/market/demo/dto/itemdetailinfo/ItemDetailDto.java, src/main/java/market/demo/dto/itemdetailinfo/ItemReviewsDto.java, src/main/java/market/demo/dto/itemdetailinfo/ReviewDto.java, src/main/java/market/demo/dto/itemdetailinfo/WishDto.java, src/main/java/market/demo/dto/mypage/MyOrderDetailDto.java, src/main/java/market/demo/dto/mypage/MyOrderDto.java, src/main/java/market/demo/dto/mypage/MyPageDto.java, src/main/java/market/demo/dto/order/OrderDto.java, src/main/java/market/demo/dto/order/OrderItemDto.java, src/main/java/market/demo/dto/search/ItemRecommendDto.java, src/main/java/market/demo/repository/AgeGenderFrequencyRepository.java, src/main/java/market/demo/repository/SearchKeywordRepository.java, src/main/java/market/demo/service/SearchService.java, src/main/resources/application.properties
- https://github.com/ASAC-marketplace/backend/issues/13
- 먼저 회원 비회원 구분은 isBlank로 구분해 놓은 상태, 추후에 aop 적용 시 수정 예정
=> 13 api 추천 검색어 api

src/main/java/market/demo/controller/item/ItemController.java, src/main/java/market/demo/controller/item/ReviewController.java, src/main/java/market/demo/domain/ApplicationTestDataInitializer.java, src/main/java/market/demo/domain/item/Review.java, src/main/java/market/demo/domain/member/Member.java, src/main/java/market/demo/dto/itemdetailinfo/ItemReviewsDto.java, src/main/java/market/demo/dto/itemdetailinfo/ReviewDto.java, src/main/java/market/demo/service/ItemService.java
- Projects 이슈 링크
- 도움돼요 checked 추가했습니다.
=> 17 api 상품설명 api
